---
- name: Download lynis
  hosts: ansible_client
  remote_user: root
  become: true
  tasks:
    - name: unzip the tar file
      ansible.builtin.unarchive:
        src: /home/kali/ansible-main/lynis-3.0.3.tar.gz
        dest: /home/
    - name: make lynis log directory
      ansible.builtin.file:
        path: /home/lynis/log
        state: directory
        mode: '0777'
    - name: start lynis script
      ansible.builtin.shell:
        cmd: cd /home/lynis/; ./lynis audit system --quick --report-file /home/lynis/log/lynis-report.dat --logfile /home/lynis/log/lynis-logfile.log > /home/lynis/log/lynis.log
    - name: unarchive linPEAS script
      ansible.builtin.unarchive:
        src: /home/kali/ansible-main/linPEAS.tar.gz
        dest: /home/
    - name: make linPEAS log directory
      ansible.builtin.file:
        path: /home/linPEAS/log
        state: directory
        mode: '0777'
    - name: start linPEAS script
      ansible.builtin.shell:
        cmd: cd /home/linPEAS; ./linpeas.sh -s > /home/linPEAS/log/linPEAS.log
    - name: copy from linPEAS to host machine
      ansible.builtin.fetch:
        src: "/home/linPEAS/log/linPEAS.log"
        dest:  /home/kali/ansible-main/log/{{ ansible_facts['default_ipv4']['address'] }}/{{ ansible_facts['date_time']['date'] }}-{{ ansible_facts['date_time']['hour'] }}-{{ ansible_facts['date_time']['minute'] }}/
        flat: yes
    - name: copy from lynius log and profile to host machine
      ansible.builtin.fetch:
        src: "/home/lynis/log/lynis.log"
        dest: /home/kali/ansible-main/log/{{ ansible_facts['default_ipv4']['address'] }}/{{ ansible_facts['date_time']['date'] }}-{{ ansible_facts['date_time']['hour'] }}-{{ ansible_facts['date_time']['minute'] }}/
        flat: yes

