---
- name: Download lynis
  hosts: windows
  remote_user: root
  become: true
  tasks:
    - name: Disable Real time protection
      win_shell: PowerShell Set-MpPreference -DisableRealtimeMonitoring 1
    - name: copy the winPEAS to windows 
      win_copy:
        src: /home/kali/ansible-main/winPEASx64.exe
        dest: C:\Users\root\Desktop\winPEASx64.exe
        mode: '0700'
          #  - name: execute command for colors in cmd
          # win_shell:
          # cmd: REG ADD HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
    - name: execute the winPeasex64.exe
      win_shell: C:\Users\root\Desktop\winPEASx64.exe cmd fast > outputWindows.txt
    - name: fetch the output log from winPease
      fetch:
       src: C:/Users/root/outputWindows.txt 
       dest: /home/kali/ansible-main/log/windows/logoutput.txt
       flat: yes
