---
- name: Download lynis
  hosts: windows
  remote_user: root
  become: runas
  vars_files:
    - /home/kali/ansible/vars/external_vars.yml
  tasks:
    - name: Create bt24 directory
      win_file:
        path: "{{ win_folder }}"
        state: directory
    - name: Add bt24 Exclusion 
      win_command: powershell.exe - 
      args:
        stdin: Add-MpPreference -ExclusionPath C:\bt24
      become: yes
      become: Administrator
    - name: Add %appdata%\local\temp exclusionPath
      win_command: powershell.exe - 
      args:
        stdin: Add-MpPreference -ExclusionPath "{{ win_local }}"
      become: yes
      become: Administratorss
    - name: copy the winPEAS to windows 
      win_copy:
        src: "{{ host_dest }}winPEASx64.exe"
        dest: "{{ win_folder }}winPEASx64.exe"
        mode: '0700'
          #  - name: execute command for colors in cmd
          # win_shell:
          # cmd: REG ADD HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
    - name: execute the winPeasex64.exe
      win_shell: 'cd C:\bt24\ ; .\winPEASx64.exe  log'
    - name: fetch the output log from winPease
      fetch:
       src: "{{ win_folder }}out.txt" 
       dest: "{{ host_dest }}log/windows/{{ hostvars[inventory_hostname]['inventory_hostname'] }}/{{ ansible_facts['date_time']['date'] }}-{{ ansible_facts['date_time']['hour'] }}:{{ ansible_facts['date_time']['minute'] }}/"
       flat: yes
    - name: remove %appdata%\local\temp exclusionPath
      win_command: powershell.exe -
      args:
        stdin: Remove-MpPreference -ExclusionPath "{{ win_local }}"
      become: Administrator
    - name: remove %appdata%\local\temp exclusionPath
      win_command: powershell.exe -
      args:
        stdin: Remove-MpPreference -ExclusionPath C:\bt24
      become: Administrator  
